// <auto-generated />
namespace GameFinder.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class GenreTest7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GenreTest7));
        
        string IMigrationMetadata.Id
        {
            get { return "202104151951086_GenreTest7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
